# See also https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

name: Build and test

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        mode: [regular, disable-ipv6, disable-set, mini, read-only, without-nl, wolfssl, Android]

    env:
      MODE: ${{ matrix.mode }}

    steps:
    - uses: actions/checkout@main

    - name: install required packages
      run: sudo bash -c "MODE=$MODE ci/install.sh"

    - name: build
      run: ci/build.sh

    - name: test
      run: ci/test.sh
